# Generated by Django 2.1.2 on 2018-11-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20181117_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
