Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, path: "bootstrap.sh", run: "always"
  config.vm.network :forwarded_port, guest: 8080, host: 8080, host_ip: "127.0.0.1"
end